name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    env:
      ENV: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

#      - name: Cache Maven dependencies
#        uses: actions/cache@v4
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build and Analyze
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=dbHere \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}  
        

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t dbhere-app .

      - name: Stop old container
        run: docker stop dbhere || true

      - name: Remove old container
        run: docker rm dbhere || true

      - name: Run new container
        run: |
          docker run -d \
            -p 8080:8080 \
            --name dbhere \
            --restart unless-stopped \
            -e SPRING_PROFILES_ACTIVE=${ENV} \
            dbhere-app